package com.ndemi.garden.gym.ui

enum class UiError {
    EMAIL_INVALID,
    PASSWORD_INVALID,
    PASSWORD_CONFIRM_INVALID,
    PASSWORD_MATCH_INVALID,
    FIRST_NAME_INVALID,
    LAST_NAME_INVALID,

    INVALID_LOGIN_CREDENTIALS,
    REGISTRATION_FAILED,
}
