package com.ndemi.garden.gym.ui

enum class UiError {
    INVALID_EMAIL,
    INVALID_PASSWORD,
    INVALID_PASSWORD_CONFIRM,
    INVALID_PASSWORD_MATCH,
    INVALID_FIRST_NAME,
    INVALID_LAST_NAME,
    INVALID_LOGIN_CREDENTIALS,
    INVALID_APARTMENT_NUMBER,
    INVALID_AMOUNT,
    INVALID_MONTH_DURATION,
    INVALID_PHONE_NUMBER,
    REGISTRATION_FAILED,
}
