package cv.domain

enum class DomainError {
    UNKNOWN,
    USER_DISABLED,
    SERVER,
    NETWORK,
    NO_DATA,
    UNAUTHORISED,
    EMAIL_ALREADY_EXISTS,
    INVALID_ARGUMENT,
    INVALID_LOGIN_CREDENTIALS,
    INVALID_PASSWORD_LENGTH,
    INVALID_SESSION_TIME,
}
